src/main/java/com/example/bookstoreapp/controllers/HealthController.java, src/main/resources/application.properties
Task: https://github.com/learning-project-01/bookstore-app/issues/1
1. APi can be accessed at http://localhost:8080/health
2. Below shows the response:
=> added health api for application

pom.xml, src/main/java/com/example/bookstoreapp/controllers/CatalogItemController.java, src/main/java/com/example/bookstoreapp/models/CatalogItem.java, src/main/java/com/example/bookstoreapp/services/CatalogItemService.java, src/main/java/com/example/bookstoreapp/services/impl/CatalogItemServiceImpl.java
Task: https://github.com/learning-project-01/bookstore-app/issues/3
Create API for CatalogItem:
```bash
curl --location --request POST 'http://localhost:8080/catalogItems' \
--data-raw '{
"name":"Item Book Two",
"price": 232.45
}'
```
List API for catalogItems
```bash
curl --location --request GET 'http://localhost:8080/catalogItems'
```
=> create and list api for catalog item

src/main/java/com/example/bookstoreapp/configs/FlywayConfig.java, src/main/resources/application.properties, src/main/resources/db/scripts/V1__CREATE_CATALOG_ITEM_TABLE.sql
Task: https://github.com/learning-project-01/bookstore-app/issues/5
Created database manually.
Flyway script added are executing successfully.
=> added flyway configuration to manage db schema

src/main/java/com/example/bookstoreapp/entities/CatalogItemEntity.java, src/main/java/com/example/bookstoreapp/models/CatalogItem.java, src/main/java/com/example/bookstoreapp/repositories/CatalogItemEntityRepository.java, src/main/java/com/example/bookstoreapp/services/impl/CatalogItemServiceImpl.java
Task: https://github.com/learning-project-01/bookstore-app/issues/8
Create API:
List API:
=> jpa integration with create and list api

pom.xml, src/main/java/com/example/bookstoreapp/controllers/UserController.java, src/main/java/com/example/bookstoreapp/entities/UserEntity.java, src/main/java/com/example/bookstoreapp/models/CatalogItem.java, src/main/java/com/example/bookstoreapp/models/User.java, src/main/java/com/example/bookstoreapp/models/UserRole.java, src/main/java/com/example/bookstoreapp/repositories/UserEntityRepository.java, src/main/java/com/example/bookstoreapp/services/UserService.java, src/main/java/com/example/bookstoreapp/services/impl/CatalogItemServiceImpl.java, src/main/java/com/example/bookstoreapp/services/impl/UserServiceImpl.java, src/main/resources/application.properties, src/main/resources/db/scripts/V2__CREATE_USER_TABLE.sql, src/main/resources/db/scripts/V3__DROP_USER_TABLE_COLUMN.sql
Task: https://github.com/learning-project-01/bookstore-app/issues/10
```bash
curl --location 'localhost:8080/user/signup' \
--data-raw '{
"email":"abcd@email.com",
"password": "abc@123",
"firstName":"John",
"lastName": "Doe",
"role": "CUSTOMER" 
}'
```
=> added user signup api

src/main/java/com/example/bookstoreapp/BookstoreAppApplication.java, src/main/java/com/example/bookstoreapp/ServletInitializer.java, src/main/java/com/example/bookstoreapp/configs/FlywayConfig.java, src/main/java/com/example/bookstoreapp/controllers/CartController.java, src/main/java/com/example/bookstoreapp/controllers/CatalogItemController.java, src/main/java/com/example/bookstoreapp/controllers/HealthController.java, src/main/java/com/example/bookstoreapp/controllers/UserController.java, src/main/java/com/example/bookstoreapp/entities/CartItemEntity.java, src/main/java/com/example/bookstoreapp/entities/CatalogItemEntity.java, src/main/java/com/example/bookstoreapp/models/Cart.java, src/main/java/com/example/bookstoreapp/models/CartItem.java, src/main/java/com/example/bookstoreapp/models/CartItemState.java, src/main/java/com/example/bookstoreapp/models/CatalogItem.java, src/main/java/com/example/bookstoreapp/models/User.java, src/main/java/com/example/bookstoreapp/repositories/CartItemEntityRepository.java, src/main/java/com/example/bookstoreapp/services/CartItemService.java, src/main/java/com/example/bookstoreapp/services/CatalogItemService.java, src/main/java/com/example/bookstoreapp/services/UserService.java, src/main/java/com/example/bookstoreapp/services/UserSessionService.java, src/main/java/com/example/bookstoreapp/services/impl/CartItemServiceImpl.java, src/main/java/com/example/bookstoreapp/services/impl/CatalogItemServiceImpl.java, src/main/java/com/example/bookstoreapp/services/impl/UserServiceImpl.java, src/main/java/com/example/bookstoreapp/services/impl/UserSessionServiceImpl.java, src/main/java/com/example/bookstoreapp/utils/IdGenerator.java, src/main/resources/db/scripts/V4__CREATE_CART_ITEM_TABLE.sql
Task: https://github.com/learning-project-01/bookstore-app/issues/13
curl --location --request POST 'localhost:8080/cart/1'
curl --location 'localhost:8080/cart'
=> added add to cart operation

src/main/java/com/example/bookstoreapp/controllers/AddressController.java, src/main/java/com/example/bookstoreapp/entities/AddressEntity.java, src/main/java/com/example/bookstoreapp/models/Address.java, src/main/java/com/example/bookstoreapp/repositories/AddressRepository.java, src/main/java/com/example/bookstoreapp/services/AddressService.java, src/main/java/com/example/bookstoreapp/services/impl/AddressServiceImpl.java, src/main/resources/db/scripts/V5__CREATE_ADDRESS_TABLE.sql
Task : https://github.com/learning-project-01/bookstore-app/issues/19
````bash
curl --location 'localhost:8080/address' \
--data '{
"line1": "Line 1",
"line2": "Line 2",
"city": "City 1",
"state": "State 1",
"country": "Country 1",
"postalCode": 123456
}'
````
````bash
curl --location 'localhost:8080/address'
````
=> address api implementation

README.md, pom.xml, src/main/resources/application.properties
Task: https://github.com/learning-project-01/bookstore-app/issues/9
=> swagger open api 3 integration

history/change.md, src/main/java/com/example/bookstoreapp/controllers/CatalogItemController.java, src/main/java/com/example/bookstoreapp/entities/CatalogItemEntity.java, src/main/java/com/example/bookstoreapp/exceptions/AppRuntimeException.java, src/main/java/com/example/bookstoreapp/models/CatalogItem.java, src/main/java/com/example/bookstoreapp/services/CatalogItemService.java, src/main/java/com/example/bookstoreapp/services/impl/CartItemServiceImpl.java, src/main/java/com/example/bookstoreapp/services/impl/CatalogItemServiceImpl.java, src/main/resources/db/scripts/V6__STOCK_QUANTITY_COLUMN.sql
Task: https://github.com/learning-project-01/bookstore-app/issues/27
```bash
curl --location --request PUT 'localhost:8080/catalogItems/1' \
--data ' {
"id": 1,
"name": "Product A",
"price": 19.99,
"stockQuantity": 1
}'
```
=> added stock quantity for catalog items

history/change.md, src/main/java/com/example/bookstoreapp/exceptions/ApplicationExceptionHandler.java, src/main/java/com/example/bookstoreapp/exceptions/ErrorInfo.java, src/main/java/com/example/bookstoreapp/services/impl/CatalogItemServiceImpl.java, src/main/java/com/example/bookstoreapp/utils/IdGenerator.java, src/test/java/com/example/bookstoreapp/models/CatalogItemTest.java, src/test/java/com/example/bookstoreapp/models/UserTest.java, src/test/java/com/example/bookstoreapp/utils/IdGeneratorTest.java
Task: https://github.com/learning-project-01/bookstore-app/issues/30
```bash
curl --location --request PUT 'localhost:8080/catalogItems/100' \
--data ' {
"id": 1,
"name": "Product A",
"price": 19.99,
"stockQuantity": 1
}'
```
=> fix put mapping of catalog | error handling

src/main/java/com/example/bookstoreapp/controllers/CartController.java, src/main/java/com/example/bookstoreapp/services/CartItemService.java, src/main/java/com/example/bookstoreapp/services/impl/CartItemServiceImpl.java
Task: https://github.com/learning-project-01/bookstore-app/issues/34
curl --location 'localhost:8080/cart/checkout'
=> implement checkout api

src/main/java/com/example/bookstoreapp/controllers/UserController.java, src/main/java/com/example/bookstoreapp/repositories/UserEntityRepository.java, src/main/java/com/example/bookstoreapp/services/UserService.java, src/main/java/com/example/bookstoreapp/services/impl/UserServiceImpl.java
Task: https://github.com/learning-project-01/bookstore-app/issues/40
curl --location 'localhost:8080/user/login' \
--data-raw '{
"email":"abcd@email.com",
"password": "abc@123"
}'
=> login api implementation

src/main/java/com/example/bookstoreapp/models/CartItem.java
**Bug - The total price was showing worng for the number of quantity selected in cart**  
Prefix:  
Postfix:  
Curl:  
`curl --location 'http://localhost:8080/cart/'
`
=> wrong total price bugfix

src/test/java/com/example/bookstoreapp/models/CartItemStateTest.java
Below is example of CartItemStateTest class. So it covers CartItemState class with 100% coverage.
=> CartItemState test case

src/main/java/com/example/bookstoreapp/services/impl/UserServiceImpl.java
=>  UUID string as a Base64 encoded

src/main/java/com/example/bookstoreapp/configs/FilterConfiguration.java, src/main/java/com/example/bookstoreapp/filters/AuthenticationFilter.java
=> configured filter for the application

src/test/java/com/example/bookstoreapp/controllers/AddressControllerTest.java, src/test/java/com/example/bookstoreapp/controllers/CartControllerTest.java, src/test/java/com/example/bookstoreapp/controllers/CatalogItemControllerTest.java, src/test/java/com/example/bookstoreapp/controllers/HealthControllerTest.java, src/test/java/com/example/bookstoreapp/services/impl/AddressServiceImplTest.java, src/test/java/com/example/bookstoreapp/services/impl/CartItemServiceImplTest.java, src/test/java/com/example/bookstoreapp/services/impl/CatalogItemServiceImplTest.java, src/test/java/com/example/bookstoreapp/services/impl/UserServiceImplTest.java, src/test/java/com/example/bookstoreapp/services/impl/UserSessionServiceImplTest.java
Closes #23
The bwlow testcases need attention as I was unable to implement them properly.
1. AddressServiceImplTest - findUserAddress()
2. CartItemServiceImplTest - getCartSummary()
3. CartItemServiceImplTest - doCheckout()
=> Unit tests for controllers/services

src/main/java/com/example/bookstoreapp/auth/impl/AuthServiceImpl.java, src/main/java/com/example/bookstoreapp/models/User.java, src/main/java/com/example/bookstoreapp/utils/AppUtils.java, src/test/java/com/example/bookstoreapp/auth/AuthServiceImplTest.java, src/test/java/com/example/bookstoreapp/auth/TokenTest.java
=> auth test cases

src/main/java/com/example/bookstoreapp/auth/cache/AuthCacheClient.java, src/main/java/com/example/bookstoreapp/cache/AbstractCacheClient.java
(cherry picked from commit 54baf760ff840a1c85603862323b05b9cdb4135c)
=> extend cache impl for cache

src/main/java/com/example/bookstoreapp/controllers/ShoppingOrderController.java, src/main/java/com/example/bookstoreapp/entities/OrderItemEntity.java, src/main/java/com/example/bookstoreapp/entities/ShoppingOrderEntity.java, src/main/java/com/example/bookstoreapp/models/CartItem.java, src/main/java/com/example/bookstoreapp/models/OrderItem.java, src/main/java/com/example/bookstoreapp/models/OrderRequest.java, src/main/java/com/example/bookstoreapp/models/ShoppingOrder.java, src/main/java/com/example/bookstoreapp/models/StatusCode.java, src/main/java/com/example/bookstoreapp/repositories/OrderItemEntityRepository.java, src/main/java/com/example/bookstoreapp/repositories/ShoppingOrderEntityRepository.java, src/main/java/com/example/bookstoreapp/services/CartItemService.java, src/main/java/com/example/bookstoreapp/services/CatalogItemService.java, src/main/java/com/example/bookstoreapp/services/OrderService.java, src/main/java/com/example/bookstoreapp/services/impl/CartItemServiceImpl.java, src/main/java/com/example/bookstoreapp/services/impl/CatalogItemServiceImpl.java, src/main/java/com/example/bookstoreapp/services/impl/OrderServiceImpl.java, src/main/java/com/example/bookstoreapp/utils/AppUtils.java, src/main/resources/application.properties, src/main/resources/db/scripts/V7__SHOPPING_ORDER_TABLE.sql
````curl
curl --location 'localhost:8080/orders' \
--header 'X-AUTH-TOKEN: YzM4MmYzODgtNjVmYy00YjY0LTlkZjUtMDQxZThlZjI4ZGYz' \
--data '{
"addressId":314972463431100
}'
````
=> place order implementation

src/main/java/com/example/bookstoreapp/controllers/MediaController.java, src/main/java/com/example/bookstoreapp/entities/CatalogItemEntity.java, src/main/java/com/example/bookstoreapp/entities/MediaEntity.java, src/main/java/com/example/bookstoreapp/filters/AuthenticationFilter.java, src/main/java/com/example/bookstoreapp/models/CartItem.java, src/main/java/com/example/bookstoreapp/models/CatalogItem.java, src/main/java/com/example/bookstoreapp/models/Media.java, src/main/java/com/example/bookstoreapp/models/MediaType.java, src/main/java/com/example/bookstoreapp/repositories/MediaRepository.java, src/main/java/com/example/bookstoreapp/services/MediaService.java, src/main/java/com/example/bookstoreapp/services/UserContextService.java, src/main/java/com/example/bookstoreapp/services/impl/CartItemServiceImpl.java, src/main/java/com/example/bookstoreapp/services/impl/MediaServiceImpl.java, src/main/resources/db/scripts/V8__CREATE_MEDIA_TABLE.sql, src/main/resources/db/scripts/V9__ADD_ITEM_LIMIT_COLUMN.sql, src/test/java/com/example/bookstoreapp/controllers/MediaControllerTest.java, src/test/java/com/example/bookstoreapp/models/CatalogItemTest.java, src/test/java/com/example/bookstoreapp/services/impl/MediaServiceImplTest.java
Added GET,POST,PUT,DELETE methods for Media-API
=> media api initial implementation

src/main/java/com/example/bookstoreapp/controllers/UserController.java, src/main/java/com/example/bookstoreapp/models/TokenRequest.java
=> logout implimentation added
